name: CI/CD Team8

on:
  push:
    branches: [ "main" ]
 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: sokolovapolina/lab5-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: user
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull sokolovapolina/lab5-app:latest
          sudo docker stop keen_burnell || true
          sudo docker rm keen_burnell || true
          sudo docker stop lab_app || true
          sudo docker rm lab_app || true
          sudo docker run -d --name lab_app -p 8080:80 sokolovapolina/lab5-app:latest
